title = "yu-my-star"
baseurl = "http://mysyutar.github.io"
languageCode = "ja-jp"
metaDataFormat = "yaml"
publishdir = "_site"
theme = "mytheme"
paginate = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  mainMenu = ["about", "work", "post"]
  author = "mysyutar"
  twitter_id = "mysyutar"
  pixiv_id = "1432163"
  github_id = "mysyutar"
  analytics = "UA-34888808-1"
  disqus = "mysyutar"
  recentLimit = 5
