title = "yu-my-star"
baseurl = "http://mysyutar.github.io"
languageCode = "ja-jp"
metaDataFormat = "yaml"
theme = "bootie-docs"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  description = "yu-my-starへようこそ！"
  analytics = "UA-34888808-1"
  mainMenu = ["about", "work", "post"]
  twitter_id = "mysyutar"
  github_id = "mysyutar"
  recentLimit = 10
