title = "yu-my-star"
baseurl = "http://mysyutar.github.io"
languageCode = "ja-jp"
metaDataFormat = "yaml"
publishdir = "_site"
theme = "mytheme"
paginate = 5

[blackfriday]
  fractions = false
  extensions = ["hardLineBreak"]

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  mainMenu = ["about", "work", "post"]
  author = "mysyutar"
  twitter_id = "mysyutar"
  pixiv_id = "mysyutar"
  nico_id = "17860340"
  nijie_id = "640804"
  horne_id = "61658"
  github_id = "mysyutar"
  analytics = "UA-34888808-1"
  disqus = "mysyutar"
  recentLimit = 5
